name: auction-auction

services:
  auction-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      PORT: 8080
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: auction
      POSTGRES_SSLMODE: disable
      POSTGRES_HOST: auction-postgres
      POSTGRES_PORT: 5433
    depends_on:
      auction-postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - auction-go-mod:/go/pkg/mod
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - auction-internal
      - rabbitmq-shared

  auction:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: auction
      POSTGRES_SSLMODE: disable
      POSTGRES_HOST: auction-postgres
      POSTGRES_PORT: 5432
    depends_on:
      auction-postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - auction-internal
      - rabbitmq-shared

  auction-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction
    volumes:
      - auction-postgres-data:/var/lib/postgresql
      - ./infra/postgres/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - auction-internal

volumes:
  auction-postgres-data:
  auction-go-mod:

networks:
  auction-internal:
  rabbitmq-shared:
    external: true
    name: auction-rabbitmq-network
